### ISSUE TITLE
Problems installing on archlinux

### ISSUE THREAD

**Issue by maotora** [plv8/plv8#215]
Hi,

Awesome project.

I have trouble installing this with archlinux. When I run `make static` I get errors relating to the code being on `python2.x` and archlinux using `python3.x` I'm no python reader / writer so I'm missing some useful tricks/hacks to make this work.

Please help.

**Comment by JerrySievert** [comment]
Hello,

The issue you are running into is that v8's build chain requires python2 to build and arch distributed pyhron3.

You need to install python2 in order for it to build - I found some notes on installing node from source (same issues): https://forum.pine64.org/showthread.php?tid=664

If you're compiling against 2.0.1, it may compile just by having the python2 package in your path, but you still may need to symlink.  (The 2.0.1 version is against a fairly recent v8, and master is even more recent).

Let me know if that solves your problem.

**Comment by maotora** [comment]
@JerrySievert  Hi, Thanks for taking your time one this thread.

Well I changed executing python to `python2.7` in `fetch` file.

**Here** 

`PYTHONDONTWRITEBYTECODE=1 exec python2 "$base_dir/fetch.py" "$@"`

But now I get this **Error** when I run `make static`

```bash

Running: gclient root
depot_tools update failed. Conflict in /home/niggacode/bin/build/plv8-2.0.2/build/depot_tools
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Traceback (most recent call last):
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient.py", line 99, in <module>
    import gclient_scm
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient_scm.py", line 980
    except subprocess2.CalledProcessError, e:
                                         ^
SyntaxError: invalid syntax
Running: gclient config --spec 'solutions = [
  {
    "url": u'"'"'https://chromium.googlesource.com/v8/v8.git'"'"',
    "managed": False,
    "name": u'"'"'v8'"'"',
    "deps_file": u'"'"'DEPS'"'"',
    "custom_deps": {},
  },
]
'
depot_tools update failed. Conflict in /home/niggacode/bin/build/plv8-2.0.2/build/depot_tools
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Traceback (most recent call last):
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient.py", line 99, in <module>
    import gclient_scm
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient_scm.py", line 980
    except subprocess2.CalledProcessError, e:
                                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 289, in run
    return checkout.init()
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 124, in init
    self.run_gclient('config', '--spec', self._format_spec())
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'config', '--spec', u'solutions = [\n  {\n    "url": u\'https://chromium.googlesource.com/v8/v8.git\',\n    "managed": False,\n    "name": u\'v8\',\n    "deps_file": u\'DEPS\',\n    "custom_deps": {},\n  },\n]\n')' returned non-zero exit status 1
/bin/sh: line 0: cd: v8: No such file or directory
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
depot_tools update failed. Conflict in /home/niggacode/bin/build/plv8-2.0.2/build/depot_tools
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Traceback (most recent call last):
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient.py", line 99, in <module>
    import gclient_scm
  File "/home/niggacode/bin/build/plv8-2.0.2/build/depot_tools/gclient_scm.py", line 980
    except subprocess2.CalledProcessError, e:
                                         ^
SyntaxError: invalid syntax
make[1]: *** [Makefile.v8:31: build/v8-git-mirror-5.4.500.43] Error 1
make: *** [Makefile:145: static] Error 2
```

**Comment by JerrySievert** [comment]
Try rm -rf build and make static again. The v8 build system is sometimes a bit fickle (outside of our control), but that should let it check out and try again. It thinks you've made changes or it was mid checkout when it failed.

**Comment by maotora** [comment]
@JerrySievert Yeah, I kinda did.

I made a change to `urlparse` I don't have that. I installed `uritools` then I used that in the `fetch.py` file I think. So I had to make a newer commit which includes that `fetch` file which I made a `python2.7` variable as explained above.

**Comment by JerrySievert** [comment]
What version of arch are you running? I can try to install a vm tomorrow and see if I can reproduce, but so far I've just been following the follies of others trying to install v8 under arch. 

As an aside, which specific tag of plv8 are you running against?

**Comment by maotora** [comment]
I'm running on Arch latest (just install and update with `pacman -Syu` and it's the same version as I am on).

I'm also using plv8 v2.0.2 and plv8 v2.0.0

Both are giving me the same errors, first it's the python interpreter (being python3) then comes the `urlparse` that I'm not sure where everybody is getting theirs but my sources only provide `uritools` which is a successor of `urlparse` (that's what they say).

I'm also using `postgresql v9.6.1`.

Hope this information is useful.

I have to say, I really appreciate the efforts @JerrySievert . 👍

**Comment by JerrySievert** [comment]
Thanks! I'll take a look either tonight or tomorrow morning (it's beer-30 in pacific time so might take a few hours). Guessing it's an issue with the python install, but should be able to track it down and get you over the hump.

**Comment by maotora** [comment]
Awesome, It was beer night with friends here too.
Looking forward to it.

**Comment by JerrySievert** [comment]
have you considered trying just a `make` against the arch supported v8 version? https://aur.archlinux.org/packages/v8/

**Comment by maotora** [comment]
Well, yeah I had that installed before even starting the whole process.

I even tried the `plv8-bin` aur version, (after all installation fixes) it crashes like how it's commented [here in the comments section](https://aur.archlinux.org/packages/plv8-bin/).

I've also ran `make static` with `archlinux v8` lib and without. It has the same effect.

**Error** msg without the `v8` library.

```
  File "/home/user/bin/build/plv8-2.0.0/build/depot_tools/fetch.py", line 63
    print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^
SyntaxError: invalid syntax
/bin/sh: line 0: cd: v8: No such file or directory
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/home/user/bin/build/plv8-2.0.0/build/depot_tools/gclient.py", line 96, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
make[1]: *** [Makefile.v8:31: build/v8-git-mirror-5.4.500.43] Error 1
make: *** [Makefile:145: static] Error 2

```

**Comment by JerrySievert** [comment]
If you have a compatible version of v8 (which arch appears to have) you can just do a normal "make" - you only need to build it statically if your os does not support a modern version of v8, or you explicitly need a specific version. 

Otherwise, you should be able to install urlparse using easy_install via python.

**Comment by maotora** [comment]
Sadly, I can't install `urlparse` due to [this](http://askubuntu.com/a/511659/280799) reasoning.. And this explains a lot, none of my `pip search urlparse` brought me exactly urlparse, rather than `urltools`, `urlparse2`, `urlparse3&4`, which meant I had to go to `fetch.py` change it's code then make a git commit.

I'm now when I run `make` or `make static` I get this error.
```
plv8.cc:9:37: fatal error: libplatform/libplatform.h: No such file or directory
 #include "libplatform/libplatform.h"
                                     ^
compilation terminated.
make: *** [Makefile:85: plv8.o] Error 1

```

I searched and came across [this](https://github.com/phpv8/v8js/issues/245) same issue but they were talking about chrom depot_tools which I have already successfully installed and still getting this issue.

**Comment by JerrySievert** [comment]
you will need to make sure the development version of the v8 lib is installed (I don't know what that is for arch).

so, I'm summoning @faddah who wrote the original guide that I linked to, perhaps he has some insight?

(@faddah, I'll happily buy you a beer next time I see you - do you have any ideas?  also, it's Tuesday, if you end up making it to bailey's this afternoon!)
