### ISSUE TITLE
Building on Amazon linux with python 2.6

### ISSUE THREAD

**Issue by zeitos** [plv8/plv8#223]
So I have my db on an Amazon linux with python 2.6 and when I try to build plv8 with make static I get 
```
Running: gclient root
Traceback (most recent call last):
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 281, in run
    if not options.force and checkout.exists():
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 80, in exists
    gclient_root = self.run_gclient('root').strip()
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/plv8-2.0.3/build/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
AttributeError: 'module' object has no attribute 'check_output'
```

is there a way to specify which python to use? (in my case `/usr/bin/python2.7`) ?

**Comment by zeitos** [comment]
ok it´s the v8 build
I'll check there
