### ISSUE TITLE
build fails if "curl" executable not available

### ISSUE THREAD

**Issue by max-l** [plv8/plv8#225]
The build depends on "curl", if not installed it fails without a helpful error message,
an error message mentioning the unmet dependency would be helpful.

```
Installing Debian Wheezy amd64 root image: /var/lib/postgresql/plv8-2.0.3/build/v8/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/c09e94d74f6efc174bd88195eee902b4350fc006/debian_wheezy_amd64_sysroot.tgz
Traceback (most recent call last):
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 232, in <module>
    sys.exit(main(sys.argv[1:]))
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 153, in main
    InstallDefaultSysroots()
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 127, in InstallDefaultSysroots
    InstallSysroot(host_arch)
  File "v8/build/linux/sysroot_scripts/install-sysroot.py", line 218, in InstallSysroot
    ['curl', '--fail', '--retry', '3', '-L', url, '-o', tarball])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in /var/lib/postgresql/plv8-2.0.3/build
make[1]: *** [build/v8-git-mirror-5.4.500.43] Error 2
make[1]: Leaving directory `/var/lib/postgresql/plv8-2.0.3'
make: *** [static] Error 2
```

**Comment by JerrySievert** [comment]
Sadly, there's nothing I can do other than document all of v8's always changing dependencies.  This is an upstream issue otherwise.
