### ISSUE TITLE
Building 1.5.3 using Debian Jessie

### ISSUE THREAD

**Issue by SeeSharpy** [plv8/plv8#263]
Hey all, wondering if anyone could provide support with attempting to build 1.5.3 in a debian jessie docker used by Postgres 9.6.6. I'm calling make static in my docker file, but seems to error everytime with the following error:

```
Traceback (most recent call last):
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2960, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2946, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2692, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 1635, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_utils.py", line 1075, in run
    self.item.run(*self.args, **self.kwargs)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 995, in run
    self.ParseDepsFile()
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 786, in ParseDepsFile
    deps_content, global_scope, local_scope, filepath)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 227, in Exec
    _visit_in_module(stmt)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 211, in _visit_in_module
    value = _gclient_eval(node.value, global_scope, filename=filename)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 191, in _gclient_eval
    return _convert(node_or_string)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 164, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    for key, value in other:
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 164, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 164, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    for key, value in other:
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 164, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 183, in _convert
    return _convert(node.left) + _convert(node.right)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 185, in _convert
    return _convert(node.left) % _convert(node.right)
TypeError: not all arguments converted during string formatting
```
We are creating docker images which match the supports AWS versions which is why we need 9.6.6 with 1.5.3

I don't have much experience with Makefiles but I have taken a look but cant seem to pinpoint the issue unless its an issue with the version of depot tools that the makefile.v8 is using.

**Comment by JerrySievert** [comment]
It looks like you’re trying to build v8 using python 3, v8 requires python 2 to build and fails with 3.

**Comment by SeeSharpy** [comment]
Thanks for the quick response @JerrySievert 

I have just checked the python version that comes with that docker version and it's 2.7.9

**Comment by JerrySievert** [comment]
that error is specifically a python 3 formatting error, since not all python 2 formatting options are supported by python 3 - are you sure that it isn't slipping in somewhere?

**Comment by SeeSharpy** [comment]
so i ran ```apt-get remove python3.*``` and all the packages it listed where not installed, at the point it goes into make static

**Comment by JerrySievert** [comment]
try connecting to a shell on the docker instance - you'll find the v8 checkout in `build` - double check with `python --version`, v8 definitely builds with 2.7.9.

you can run a build of v8 yourself - if there is no v8 directory, you will need to run:

```
$ fetch v8
```

(fetch is in the depot_tools directory)

then check out the correct version of v8, then run:

```
$ gclient sync
```

at which point:

```
$ make native
```

should start.

I'd suggest hitting the v8 groups if you're still having problems, but that version of v8 is extremely out of date (plv8 2.3.0 is on 6.4.388) and they'd likely just tell you to update - and the build system is quite different now as well.

**Comment by SeeSharpy** [comment]
may have missed some of the error which i was getting earlier, apologies

```Running: gclient sync --with_branch_heads
    sys.exit(main())
  File "/tmp/build/plv8-1.5.3/build/depot_tools/fetch.py", line 301, in main
    return run(options, spec, root)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/fetch.py", line 295, in run
    return checkout.init()
  File "/tmp/build/plv8-1.5.3/build/depot_tools/fetch.py", line 137, in init
    self.run_gclient(*sync_cmd)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/fetch.py", line 82, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/fetch.py", line 71, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
Previous HEAD position was f52d005... [iterpreter] Share feedback slots for global stores to the same variable.
HEAD is now at 89756fb... Version 4.3.66
/tmp/build/plv8-1.5.3/build/.gclient_entries missing, .gclient file in parent directory /tmp/build/plv8-1.5.3/build might not be the file you want to use.

v8/build/gyp (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/gyp.git /tmp/build/plv8-1.5.3/build/v8/build/_gclient_gyp_7LKglf' in '/tmp/build/plv8-1.5.3/build'
[0:00:00] Cloning into '/tmp/build/plv8-1.5.3/build/v8/build/_gclient_gyp_7LKglf'...
[0:00:00] remote: Sending approximately 11.59 MiB ...
[0:00:00] Receiving objects:   0% (1/18077)
[0:00:00] Receiving objects:  10% (1808/18077)
[0:00:01] Receiving objects:  97% (17535/18077), 8.66 MiB | 8.64 MiB/s
[0:00:01] remote: Total 18077 (delta 11331), reused 18077 (delta 11331)
[0:00:01] Receiving objects: 100% (18077/18077), 8.66 MiB | 8.64 MiB/s
[0:00:01] Resolving deltas:   0% (0/11331)
[0:00:01] Resolving deltas:  10% (1134/11331)
[0:00:02] Resolving deltas: 100% (11331/11331)
[0:00:02] Checking connectivity... done.
[0:00:02] Checked out d174d75bf69c682cb62af9187879e01513b35e52 to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch to
an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.```

not sure if that changes the advice or not

**Comment by JerrySievert** [comment]
that's telling you that you're trying to re-build in a v8 build directory that you've used before, which is probably not what you want.

v8's build tools expect a clean slate, and will end up with an error if you fail a build, change something, and try to pick back up.

before continuing with the same build, I'd suggest trying a build without docker, where you're in control, on a clean slate.  once you have a verifiable build with the correct version of python, then drop it into docker and let it build.

**Comment by SeeSharpy** [comment]
Tried that last night installing it on a Debian instance and going through what the docker file would do, and at all stages, it was Python 2.7.9.

Not sure how it would think it was being built in the same place, as it uses a new container to build every time.

**Comment by JerrySievert** [comment]
Why not just use of one the many pre built docker images? Like https://hub.docker.com/r/clkao/postgres-plv8/

**Comment by SeeSharpy** [comment]
because it doesn't allow us to select the correct version of Postgres 

clkao 9.6 - 1.5.3 is also failing nightly due to the same issue.
