### ISSUE TITLE
Ubuntu: static build of v8 component performed in release v2.3.0 requires pkg-config

### ISSUE THREAD

**Issue by whileoneloop** [plv8/plv8#264]
If you're trying to build v2.3.0 on ubuntu, ensure you have pkg-config installed to avoid the error below.

`apt-get install pkg-config`

Otherwise, you will see an error after running:

`make`

It will take some time to download v8 , then fail with an error like:
```
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
```

Adding -vv to get more info will output:
```
Traceback (most recent call last):
  File "/tmp/plv8-2.3.0/build/v8/build/config/linux/pkg-config.py", line 232, in <module>
    sys.exit(main())
  File "/tmp/plv8-2.3.0/build/v8/build/config/linux/pkg-config.py", line 139, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/tmp/plv8-2.3.0/build/v8/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:83:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:173:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------
GN gen failed: 1
```

If you encounter other errors, they may be due to other missing dependencies during the v8 build, checkout the guide here: 

https://github.com/v8/v8/wiki/Building-from-Source

Which mentions the need to run this once to ensure dependencies are present:
 
`./build/install-build-deps.sh`

**Comment by JerrySievert** [comment]
yes, you cannot build *any* extensions for postgres without it.

**Comment by JerrySievert** [comment]
at least in linux.

**Comment by whileoneloop** [comment]
I was able to build 2.0.3 without it - on the same ubuntu version :).
