### ISSUE TITLE
[MAKE FAILURE] Makefile:39: recipe for target 'build/v8' failed

### ISSUE THREAD

**Issue by lucduong** [plv8/plv8#282]
I followed the setup guide from homepage.`https://plv8.github.io/#installing-plv8` but I got the error. I tried to `make` many times but still got the same errors:

```
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:39: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
```

My Environment:
```
OS: 16.04

NodeJS: I installed nodejs before (8.11.2)

Postgresql: psql (PostgreSQL) 9.5.12

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

packages: postgresql-server-dev-9.5, libpq-dev
```

I tried 2 versions: `v2.3.3` & `v2.3.4`
```
$ wget https://github.com/plv8/plv8/archive/v2.3.3.tar.gz
$ tar -xvzf v2.3.3.tar.gz
$ cd plv8-2.3.3
$ make
```

I already tried with `sudo make`, `make static`, ... But no one give me the success

**Comment by JerrySievert** [comment]
it appears that your `fetch` step failed.  can you please include the full log of the `make`, and not just the error from the v8 python process?

you may need to remove the `build` directory to get the full logs.

**Comment by lucduong** [comment]
@JerrySievert Thanks for your support. I have tried install `sudo apt-get install libc++-dev`. And make by using `make static` and everything works well.
