### ISSUE TITLE
MacOS build error

### ISSUE THREAD

**Issue by dboris** [plv8/plv8#284]
macOS 10.13.4, Postgresql  10.3 installed via Macports.
```
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
[1/1] Regenerating ninja files
[597/615] LINK ./mksnapshot
FAILED: mksnapshot 
TOOL_VERSION=1528136289 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -isysroot ../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9.0 -Wl,-ObjC -Wl,-dead_strip -o "./mksnapshot" -Wl,-filelist,"./mksnapshot.rsp"  
ld: unexpected token: !tapi-tbd-v3 file '../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
    subprocess.check_call(compiler_driver_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-isysroot', '../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk', '-mmacosx-version-min=10.9.0', '-Wl,-ObjC', '-Wl,-dead_strip', '-o', './mksnapshot', '-Wl,-filelist,./mksnapshot.rsp']' returned non-zero exit status 254
ninja: build stopped: subcommand failed.
```

**Comment by JerrySievert** [comment]
it appears that `clang`, the c compiler, crashed while compiling `v8`: `clang: error: unable to execute command: Segmentation fault: 11`.

you can try running `make` again without changes, and if that fails, remove the `build` directory and then run `make`.

**Comment by dboris** [comment]
Same error after removing `build` and running `make` again.

**Comment by JerrySievert** [comment]
can you please include the full output from `make`?

**Comment by dboris** [comment]
```
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 19.52 MiB ...
remote: Total 26467 (delta 19151), reused 26467 (delta 19151)
Receiving objects: 100% (26467/26467), 19.52 MiB | 4.77 MiB/s, done.
Resolving deltas: 100% (19151/19151), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /Users/boris/src/pg/plv8-2.3.3/build/_gclient_v8_nzuAK1' in '/Users/boris/src/pg/plv8-2.3.3/build'
Cloning into '/Users/boris/src/pg/plv8-2.3.3/build/_gclient_v8_nzuAK1'...
remote: Sending approximately 307.72 MiB ...        
remote: Counting objects: 7714, done        
remote: Finding sources: 100% (53/53)           
remote: Total 561884 (delta 476267), reused 561859 (delta 476267)        
Receiving objects: 100% (561884/561884), 308.01 MiB | 19.61 MiB/s, done.
Resolving deltas: 100% (476267/476267), done.
Syncing projects:  95% (22/23) v8/test/test262/data                     
[0:02:18] Still working on:
[0:02:18]   v8/third_party/icu

[0:02:28] Still working on:
[0:02:28]   v8/third_party/icu

[0:02:28] Still working on:
[0:02:28]   v8/third_party/icu
Syncing projects: 100% (23/23), done.              

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/buildtools/mac/clang-format...
Downloading 1 files took 7.248924 second(s)
Running hooks:  32% ( 9/28) luci-go_mac       
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/tools/luci-go/mac64/isolate...
Downloading 1 files took 6.481683 second(s)
Running hooks:  42% (12/28) gn_mac       
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/buildtools/mac/gn...
Downloading 1 files took 5.806979 second(s)
Running hooks:  50% (14/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 5.881523 second(s)
Running hooks:  53% (15/28) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 6.555714 second(s)
Running hooks:  89% (25/28) clang               
________ running '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' in '/Users/boris/src/pg/plv8-2.3.3/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-332838-1.tgz .......... Done.
Running hooks: 100% (28/28), done.        
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was 66f3e8f64d [wasm] Enable sign extension opcodes by default
HEAD is now at d481edab15 Version 6.4.388.40
Syncing projects: 100% (23/23), done.                                   

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/tools/luci-go/mac64/isolate...
Downloading 1 files took 7.066480 second(s)
Running hooks:  47% (11/23) gn_mac       
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/buildtools/mac/gn...
Downloading 1 files took 5.846429 second(s)
Running hooks:  56% (13/23) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/Users/boris/src/pg/plv8-2.3.3/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 5.722544 second(s)
Running hooks:  86% (20/23) clang               
________ running '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' in '/Users/boris/src/pg/plv8-2.3.3/build'
Updating Clang to 318667-1...
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-318667-1.tgz .......... Done.
Creating directory /Users/boris/src/pg/plv8-2.3.3/build/v8/third_party/llvm-build/Release+Asserts
clang 318667-1 unpacked
Running hooks:  95% (22/23) regyp_if_needed
________ running '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/gypfiles/gyp_v8 --running-as-hook' in '/Users/boris/src/pg/plv8-2.3.3/build'
GYP is now disabled by default in runhooks.

If you really want to run this, either run 
`python gypfiles/gyp_v8` explicitly by hand 
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.
Running hooks: 100% (23/23), done.         

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.

cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
[1/1] Regenerating ninja files
[597/615] LINK ./mksnapshot
FAILED: mksnapshot 
TOOL_VERSION=1528137855 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -isysroot ../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9.0 -Wl,-ObjC -Wl,-dead_strip -o "./mksnapshot" -Wl,-filelist,"./mksnapshot.rsp"  
ld: unexpected token: !tapi-tbd-v3 file '../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libc++.tbd' for architecture x86_64
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
    subprocess.check_call(compiler_driver_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-isysroot', '../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk', '-mmacosx-version-min=10.9.0', '-Wl,-ObjC', '-Wl,-dead_strip', '-o', './mksnapshot', '-Wl,-filelist,./mksnapshot.rsp']' returned non-zero exit status 254
ninja: build stopped: subcommand failed.
make: *** [v8] Error 1
```

**Comment by JerrySievert** [comment]
it appears that something from `macports` has installed its own custom compiler and linker into your path, and is being used instead of Apple's Xcode, which is what should be being used.

you can verify this by running: `which ld`:

```
$ which ld
/usr/bin/ld
```

if you do not see `/usr/bin/ld`, then the version of `ld` that `macports` installs is not 100% compatible (it does not understand tbd).  likely, you will see `/opt/local/bin/ld`.

you can get more information from https://bugs.chromium.org/p/v8/issues/detail?id=5994 and https://forums.adobe.com/thread/2214483, but there are a couple of ways to work around this:

* remove the directory that `macports` installed `ld` in from your path, and recompile with Apple's compilation tools
* `sudo port install ld64 +ld64_xcode` to install the correct version of `ld`

give one or both of those a try, and you should be able to move forward.

**Comment by dboris** [comment]
That was it. `sudo port install ld64 +ld64_xcode` did it.

**Comment by reza627** [comment]
By running : 
$ sudo port install ld64 +ld64_xcode
I had below error:

Error: Current platform "darwin 18" does not match expected platform "darwin 17"
Error: If you upgraded your OS, please follow the migration instructions: https://trac.macports.org/wiki/Migration
OS platform mismatch
    while executing
"mportinit ui_options global_options global_variations"
Error: /opt/local/bin/port: Failed to initialize MacPorts, OS platform mismatch

I have MacOS Mojave 10.12.1 and XCode 10.1

**Comment by JerrySievert** [comment]
you'll want to open up an issue on macports for that, but here's the other (better) way to solve it:

* remove the directory that macports installed ld in from your path, and recompile with Apple's compilation tools

you're using an alternate toolchain to build, that isn't fully compatible with macOS, whereas Xcode is compatible.  best to just use Xcode :)

**Comment by reza627** [comment]
Thanks, Jerry. Now the problem solved.
