### ISSUE TITLE
Uduntu: Recipe for target 'build/v8' failed

### ISSUE THREAD

**Issue by eliaspanagiotidis** [plv8/plv8#295]
Hi,

I tried to build version 2.3.7 in a Ubuntu 16.04 VM in Azure, but it was failed with the message that follows. I also tried version 2.3.3 with exactly the same result. Then I attempted to build both versions in another VN (Ubuntu 18.04), but the error was the same.

I'd appreciate any help.
Thanks in advance.

`
OS:
Ubuntu 16.04

$ git --version
git version 2.7.4

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ python --version
Python 2.7.12

$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ apt-get install libc++-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc++-dev is already the newest version (3.7.0-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ apt-get install libc++abi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc++abi-dev is already the newest version (3.7.0-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

...
...
[0:01:20] Still working on:
[0:01:20]   v8
Checking connectivity... done.

[0:01:30] Still working on:
[0:01:30]   v8

[0:01:40] Still working on:
[0:01:40]   v8
Syncing projects:   0% ( 0/ 2)
[0:01:43] Still working on:
[0:01:43]   v8
Syncing projects: 100% (24/24), done.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 30.087963 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 30.12 secs
Running hooks:  35% (10/28) luci-go_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 5.073288 second(s)
Running hooks:  46% (13/28) gn_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 4.551819 second(s)
Running hooks:  50% (14/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 15.169645 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' took 15.20 secs
Running hooks:  53% (15/28) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 4.967827 second(s)
Running hooks:  64% (18/28) sysroot_x86
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/pind/plv8/plv8-2.3.7/build'
Installing Debian sid i386 root image: /home/pind/plv8/plv8-2.3.7/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/1015a998c2adf188813cca60b558b0ea1a0b6ced/debian_sid_i386_sysroot.tar.xz
Running hooks:  71% (20/28) sysroot_x64
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/pind/plv8/plv8-2.3.7/build'
Installing Debian sid amd64 root image: /home/pind/plv8/plv8-2.3.7/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/1015a998c2adf188813cca60b558b0ea1a0b6ced/debian_sid_amd64_sysroot.tar.xz
Running hooks:  85% (24/28) binutils
________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 4.498597 second(s)
Downloading /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  89% (25/28) clang
________ running '/usr/bin/python v8/tools/clang/scripts/update.py' in '/home/pind/plv8/plv8-2.3.7/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-336424-1.tgz .......... Done.
Running hooks: 100% (28/28), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was 1bd4832... [cleanup] Fix uses of V8_DEPRECATE_SOON methods in v8
HEAD is now at d481eda... Version 6.4.388.40
Running depot tools as root is sad.
Syncing projects: 100% (23/23), done.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 7.143179 second(s)
Running hooks:  52% (12/23) gn_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 8.062310 second(s)
Running hooks:  56% (13/23) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 5.456521 second(s)
Running hooks:  65% (15/23) sysroot
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/home/pind/plv8/plv8-2.3.7/build'
Installing Debian Stretch amd64 root image: /home/pind/plv8/plv8-2.3.7/build/v8/build/linux/debian_stretch_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/debian_stretch_amd64_sysroot.tar.xz
Installing Debian Stretch i386 root image: /home/pind/plv8/plv8-2.3.7/build/v8/build/linux/debian_stretch_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/debian_stretch_i386_sysroot.tar.xz
Hook '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 42.28 secs
Running hooks:  82% (19/23) binutils
________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/home/pind/plv8/plv8-2.3.7/build'
0> Downloading /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 4.691616 second(s)
Downloading /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/pind/plv8/plv8-2.3.7/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  86% (20/23) clang
________ running '/usr/bin/python v8/tools/clang/scripts/update.py' in '/home/pind/plv8/plv8-2.3.7/build'
Updating Clang to 318667-1...
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-318667-1.tgz .......... Done.
Creating directory /home/pind/plv8/plv8-2.3.7/build/v8/third_party/llvm-build/Release+Asserts
clang 318667-1 unpacked
Running hooks:  95% (22/23) regyp_if_needed
________ running '/usr/bin/python v8/gypfiles/gyp_v8 --running-as-hook' in '/home/pind/plv8/plv8-2.3.7/build'
GYP is now disabled by default in runhooks.

If you really want to run this, either run
`python gypfiles/gyp_v8` explicitly by hand
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.
Running hooks: 100% (23/23), done.

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.

WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.

WARNING: 'v8/third_party/proguard' is no longer part of this client.  It is recommended that you manually remove it.

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
`

**Comment by eliaspanagiotidis** [comment]
Yes! It worked. Many thanks Jerry!
