### ISSUE TITLE
Unable to build under Alpine Linux

### ISSUE THREAD

**Issue by unoexperto** [plv8/plv8#299]
Hey guys. I'm trying to build plv 2.3.7 in Alpine Linux (popular base OS for docker images).

Not sure what prerequisites would be but I installed this

`apk add --update ca-certificates curl build-base git python postgresql-dev=10.4-r0`

on make or make static I get following error:

```
[E2018-08-08T13:07:13.615583Z 4285 0 annotate.go:242] #18 runtime/asm_amd64.s:2361 - runtime.goexit()
]

Downloading 1 files took 3.933089 second(s)
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /tmp/build/plv8-2.3.7/build

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
make: *** [Makefile:35: build/v8] Error 1
```

What am I missing ?

**Comment by JerrySievert** [comment]
can you please do the following and paste the output?  it will help track down what dependencies you are missing to build v8:

```
cd build/v8
tools/mb/mb.py -vv gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release out.gn/x64.release
```

**Comment by herophuong** [comment]
I am having the same issue. Before OP's error appeared, there was this error with gclient:

```
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 306, in <module>
    sys.exit(main())
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 301, in main
    return run(options, spec, root)
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 295, in run
    return checkout.init()
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 137, in init
    self.run_gclient(*sync_cmd)
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 82, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/tmp/build/plv8-2.1.2/build/depot_tools/fetch.py", line 71, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
Previous HEAD position was 81c9e3936b [Atomics] Add use counter for Atomics.{wake, notify}
HEAD is now at 819af83f01 Version 5.8.301
/tmp/build/plv8-2.1.2/build/.gclient_entries missing, .gclient file in parent directory /tmp/build/plv8-2.1.2/build might not be the file you want to use.
```

**Comment by herophuong** [comment]
And also this error from download_from_google_storage:

```
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/tmp/build/plv8-2.1.2/build'
0> Failed to fetch file gs://chromium-clang-format/416d0a9dc7ad199afd28df9e58b1b2953d33308e for v8/buildtools/linux64/clang-format, skipping. [Err: [E2018-09-21T01:38:38.185048Z 1846 0 venv.go:942] Command (cwd=): [/root/.vpython-root/17ddb1/bin/python -B -E -s -m pip install --isolated --compile --no-index --find-links /tmp/vpython_bootstrap950018687/packages --requirement /tmp/vpython_bootstrap950018687/requirements.txt --no-binary=:none: --only-binary=:all: --use-wheel]
Process output:
Collecting appdirs==1.4.3 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 1))
Collecting asn1crypto==0.22.0 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 2))
Collecting boto==2.48.0 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 3))
Collecting cffi==1.10.0 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 4))
  Could not find a version that satisfies the requirement cffi==1.10.0 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 4)) (from versions: )
No matching distribution found for cffi==1.10.0 (from -r /tmp/vpython_bootstrap950018687/requirements.txt (line 4))
```

**Comment by JerrySievert** [comment]
this is specific to alpine and v8, see the thread here: https://groups.google.com/forum/#!topic/v8-users/hQf8jn7BJRE

there's more specific information available here: https://gist.github.com/tylerchr/15a74b05944cfb90729db6a51265b6c9

you'd be on your own getting it to build, but the `Makefile` should help you *if* you're able to get v8 itself to build (the gist link will have the background, you'll want to read that thoroughly).

**Comment by alexeyfadeev** [comment]
You can use our build for alpine.
[Image on dockerhub](https://hub.docker.com/r/sibedge/postgres-plv8)
[Dockerfile example](https://github.com/sibedge-llc/plv8-dockerfiles/blob/master/alpine/Dockerfile)
