### ISSUE TITLE
Build Error for PLV8 2.3.8 with PostgreSQL 11 on Windows 10  - error: loading 'build.ninja'

### ISSUE THREAD

**Issue by vladeck** [plv8/plv8#310]
After running `bootstrap.bat` (did all previous steps as described in [Building for Windows](https://plv8.github.io/#building-for-windows)) I get an error:

```
...

Fetch also does not yet deal with partial checkouts, so if fetch
failed, delete the checkout and start over (crbug.com/230691).
HEAD is now at d481edab15 Version 6.4.388.40
Syncing projects: 100% (23/23), done.
Running hooks:  95% (22/23) regyp_if_needed
________ running 'C:\Projects\plv8\windows\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe v8/gypfiles/gyp_v8 --running-as-hook' in 'C:\Projects\plv8\windows\vendor'
Skipping gyp_v8 due to GYP_CHROMIUM_NO_ACTION env var.
Running hooks: 100% (23/23), done.

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "C:\Projects\plv8\windows\vendor\v8\tools\dev\v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "C:\Projects\plv8\windows\vendor\v8\tools\dev\v8gen.py", line 298, in main
    return self._options.func()
  File "C:\Projects\plv8\windows\vendor\v8\tools\dev\v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "C:\Projects\plv8\windows\vendor\v8\tools\dev\v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "C:\Python27\lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', '-u', 'tools\\mb\\mb.py', 'gen', '-f', 'infra\\mb\\mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
ninja: error: loading 'build.ninja': The system cannot find the file specified.

ninja: Entering directory `out.gn\x64.release'
```

I have the following:

git version 2.18.0.windows.1
GNU patch 2.7.4
UnZip 6.00
Python 2.7.6
Visual Studio 2015/2017 installed (Community Edition)

Let me know If I can provide any additional data to track down the issue.

**Comment by JerrySievert** [comment]
to start with, it appears that the checkout failed and was restarted:

```
Fetch also does not yet deal with partial checkouts, so if fetch
failed, delete the checkout and start over (crbug.com/230691).
```

so likely the v8 repo was in a weird state that it cannot recover from.

you can also find out more as to why it is failing by running:

```
python tools\mb\mb.py gen -f infra\mb\mb_config.pyl -m developer_default -b x64.release out.gn/x64.release -vv
```

from the `v8` directory, which is where it is failing.

**Comment by vladeck** [comment]
Checkout hasn't failed, I just tried running `bootstrap.bat` multiple times, each time I cleaned up the repo - made no common sense to delete/re-checkout everything.

After running the command you provided from `windows\vendor\v8` directory, this is what I got:

![plv8_issue_310_001](https://user-images.githubusercontent.com/16443718/47946639-9a88e880-df0e-11e8-984c-85f43aa403a2.png)

Let me know if you need any additional info from me.

**Comment by JerrySievert** [comment]
can you paste the contents of `out.gn\x64.release\args.gn`?

if that's complete, it should be possible to build.

**Comment by vladeck** [comment]
Sure, here is the contents of `out.gn\x64.release\args.gn`:

```
is_debug = false
target_cpu = "x64"
```

**Comment by vladeck** [comment]
Closing due to inactivity - I'm giving up :)
